version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - npm install -g pnpm
      - pnpm i
      - pnpm build

artifacts:
  files:
    - '**/*'
  base-directory: 'public'
