version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

    commands:
      npm install -g pnpm
      pnpm add -g pnpm
      pnpm i

  build:
    commands:
      - pnpm build

artifacts:
  files:
    - '**/*'
  base-directory: 'public'
